/**
 * Shared artifact assembly logic used by both streaming and non-streaming runners.
 * Prefers agent-decided content, falls back to deterministic templates.
 */

import type { AgentChatOutput, ArtifactSpec, ChatResponse, Dataset } from "@/lib/schemas/bokchoys";
import {
  buildChartReportArtifact,
  buildCommsPlanArtifact,
  buildIdeaBoardArtifact,
  buildKpiDashboardArtifact,
  buildProgramCalendarArtifact,
  buildSlidesArtifact,
  buildTableArtifact,
  generateProgramCalendar,
} from "@/lib/tools";
import { analyzeMultipleDatasets } from "@/lib/tools/multi-analysis";

function createId(prefix: string) {
  return `${prefix}-${Math.random().toString(36).slice(2, 10)}`;
}

/* ─── Trace builder ─── */

export function buildTrace(
  intent: ChatResponse["intent"],
  datasetsUsed: string[],
  agentDecided: boolean,
): ChatResponse["trace"] {
  const how = agentDecided
    ? "AI agent decided all content (KPIs, tables, charts, insights)."
    : "Used template-based fallback because agent didn't return structured content.";
  const data = datasetsUsed.length > 0
    ? `Analyzed: ${datasetsUsed.join(", ")}.`
    : "No datasets used.";

  const base = { mode: "openai" as const, intent, notes: [how, data] };

  if (intent === "brainstorm") {
    return { ...base, specialists: ["MasterHRAgent", "HRStrategistAgent"], tools: ["hr_strategist"], skills: ["wellbeing-program-ideation", "hr-engagement-design", "data-analysis", "artifact-composition"] };
  }
  if (intent === "design_program") {
    return { ...base, specialists: ["MasterHRAgent", "ProgramDesignerAgent", "CommsPlannerAgent"], tools: ["program_designer", "comms_planner"], skills: ["hr-engagement-design", "game-selection", "communication-strategy", "artifact-composition"] };
  }
  if (intent === "analyze_data") {
    return { ...base, specialists: ["MasterHRAgent", "InsightsAnalystAgent"], tools: ["insights_analyst", "multi_dataset_query"], skills: ["data-analysis", "artifact-composition"] };
  }
  return { ...base, specialists: ["MasterHRAgent", "InsightsAnalystAgent", "ReportComposerAgent"], tools: ["insights_analyst", "report_composer", "multi_dataset_query"], skills: ["data-analysis", "executive-reporting", "artifact-composition"] };
}

/* ─── Agent-decided artifact builders ─── */

function buildAgentKpi(output: AgentChatOutput): ArtifactSpec | null {
  if (!output.kpis || output.kpis.length === 0) return null;
  return { id: createId("artifact"), kind: "kpi_dashboard", title: output.kpiTitle || "Dashboard", summary: output.kpiSummary || "Key metrics from your data.", kpis: output.kpis, insights: (output.insights ?? []).map((i) => i.text) };
}

function buildAgentTables(output: AgentChatOutput): ArtifactSpec[] {
  if (!output.tables || output.tables.length === 0) return [];
  return output.tables.map((t) => ({
    id: createId("artifact"),
    kind: "table_report" as const,
    title: t.title,
    summary: t.summary,
    columns: t.columns,
    rows: t.rows.map((row) => {
      const clean: Record<string, string | number> = {};
      for (const [k, v] of Object.entries(row)) {
        clean[k] = v == null ? "" : typeof v === "boolean" ? String(v) : (v as string | number);
      }
      return clean;
    }),
  }));
}

function buildAgentCharts(output: AgentChatOutput): ArtifactSpec | null {
  if (!output.charts || output.charts.length === 0) return null;
  return { id: createId("artifact"), kind: "chart_report", title: "Visual analysis", summary: output.reasoningSummary || "Charts chosen by the AI agent.", charts: output.charts.map((c) => ({ id: createId("chart"), type: c.type, title: c.title, summary: c.summary, series: c.series })) };
}

function buildAgentSlides(output: AgentChatOutput): ArtifactSpec | null {
  if (!output.slides || output.slides.length === 0) return null;
  return { id: createId("artifact"), kind: "slides_report", title: output.slideTitle || "Leadership summary", summary: output.reasoningSummary || "Report generated by AI.", slides: output.slides };
}

function buildAgentIdeaBoard(output: AgentChatOutput): ArtifactSpec | null {
  if (!output.ideas || output.ideas.length === 0) return null;
  return { id: createId("artifact"), kind: "idea_board", title: "Ideas for your request", summary: output.reasoningSummary || "Program directions based on your brief.", followUpQuestion: output.followUpQuestion || "Which direction interests you?", ideas: output.ideas };
}

function buildAgentProgram(output: AgentChatOutput): ArtifactSpec | null {
  if (!output.programDays || output.programDays.length === 0) return null;
  return {
    id: createId("artifact"),
    kind: "program_calendar",
    title: output.programTitle || "Program draft",
    objective: output.programObjective || "",
    cadence: output.programCadence || "",
    days: output.programDays.map((day) => ({
      dayLabel: day.dayLabel,
      theme: day.theme,
      focus: day.focus,
      activities: day.activities.map((a) => ({
        id: createId(a.type), type: a.type, title: a.title, description: a.description, template: null, recommendedDay: a.day, pollQuestions: a.pollQuestions, surveyQuestions: a.surveyQuestions,
      })),
    })),
  };
}

function buildAgentComms(output: AgentChatOutput): ArtifactSpec | null {
  if (!output.commsMessages || output.commsMessages.length === 0) return null;
  const channelsUsed = [...new Set(output.commsMessages.map((m) => m.channel))];
  return {
    id: createId("artifact"),
    kind: "comms_plan",
    title: `${output.programTitle || "Program"} communications plan`,
    channelsUsed,
    messages: output.commsMessages.map((m) => ({ id: createId("msg"), ...m, editableByHr: true })),
  };
}

/* ─── Main assembly: prefer agent content, fallback to templates ─── */

export function buildArtifactsFromOutput(input: {
  message: string;
  allDatasets: Dataset[];
  output: AgentChatOutput;
}): { artifacts: ArtifactSpec[]; datasetsUsed: string[]; agentDecided: boolean } & Omit<ChatResponse, "message" | "trace" | "artifacts"> {
  const { output, allDatasets } = input;

  /* BRAINSTORM */
  if (output.intent === "brainstorm") {
    const board = buildAgentIdeaBoard(output);
    if (board) return { intent: output.intent, artifacts: [board], datasetsUsed: output.datasetsUsed ?? [], agentDecided: true };
    return { intent: output.intent, artifacts: [buildIdeaBoardArtifact(input.message, allDatasets)], datasetsUsed: [], agentDecided: false };
  }

  /* DESIGN PROGRAM */
  if (output.intent === "design_program") {
    const prog = buildAgentProgram(output);
    const comms = buildAgentComms(output);
    if (prog) {
      const arts: ArtifactSpec[] = [prog];
      if (comms) arts.push(comms);
      return { intent: output.intent, artifacts: arts, datasetsUsed: [], agentDecided: true };
    }
    const draft = generateProgramCalendar({ brief: input.message });
    return { intent: output.intent, programDraft: draft, artifacts: [buildProgramCalendarArtifact(draft), buildCommsPlanArtifact(draft)], datasetsUsed: [], agentDecided: false };
  }

  /* ANALYZE / REPORT — try agent-decided first */
  const agentArts: ArtifactSpec[] = [];
  const kpi = buildAgentKpi(output); if (kpi) agentArts.push(kpi);
  agentArts.push(...buildAgentTables(output));
  const charts = buildAgentCharts(output); if (charts) agentArts.push(charts);
  const slides = buildAgentSlides(output); if (slides) agentArts.push(slides);

  if (agentArts.length > 0) {
    return { intent: output.intent, artifacts: agentArts, datasetsUsed: output.datasetsUsed ?? [], agentDecided: true };
  }

  /* Fallback: deterministic analysis */
  const multi = analyzeMultipleDatasets({ allDatasets, query: input.message });
  const dsUsed = multi.selectedDatasets.map((d) => d.name);
  const combined = {
    id: `multi-${Date.now()}`, datasetId: "multi", summary: multi.overallSummary,
    rowCount: multi.combinedMetricRows.length, columnCount: 3,
    keyFindings: multi.combinedFindings, metricRows: multi.combinedMetricRows,
  };

  const fallback: ArtifactSpec[] = [
    buildKpiDashboardArtifact({ analysis: combined, allDatasets }),
    buildTableArtifact(combined),
    buildChartReportArtifact(combined),
  ];
  if (output.intent === "build_report") fallback.push(buildSlidesArtifact(combined));

  return { intent: output.intent, analysis: combined, artifacts: fallback, datasetsUsed: dsUsed, agentDecided: false };
}
