import { classifyIntent } from "@/lib/agents/intent";
import { ensureOpenAiApiKeyLoaded } from "@/lib/config/openai-key";
import { loadPrompt } from "@/lib/prompts/load-prompt";
import type { AgentChatOutput, ArtifactSpec, ChatResponse, Dataset } from "@/lib/schemas/bokchoys";
import { AgentChatOutputSchema, ChatResponseSchema } from "@/lib/schemas/bokchoys";
import { ensureAllSampleDatasetsLoaded, getDatasetById } from "@/lib/store/memory";
import {
  buildChartReportArtifact,
  buildCommsPlanArtifact,
  buildIdeaBoardArtifact,
  buildKpiDashboardArtifact,
  buildProgramCalendarArtifact,
  buildSlidesArtifact,
  buildTableArtifact,
  generateProgramCalendar,
} from "@/lib/tools";
import { analyzeMultipleDatasets } from "@/lib/tools/multi-analysis";

function createId(prefix: string) {
  return `${prefix}-${Math.random().toString(36).slice(2, 10)}`;
}

/* ─── Trace builder ─── */

function buildTrace(
  intent: ChatResponse["intent"],
  datasetsUsed: string[],
  agentDecided: boolean,
): ChatResponse["trace"] {
  const how = agentDecided
    ? "AI agent decided all content (KPIs, tables, charts, insights)."
    : "Used template-based fallback because agent didn't return structured content.";
  const data = datasetsUsed.length > 0
    ? `Analyzed: ${datasetsUsed.join(", ")}.`
    : "No datasets used.";

  const base = { mode: "openai" as const, intent, notes: [how, data] };

  if (intent === "brainstorm") {
    return { ...base, specialists: ["MasterHRAgent", "HRStrategistAgent"], tools: ["hr_strategist"], skills: ["wellbeing-program-ideation", "hr-engagement-design", "data-analysis", "artifact-composition"] };
  }
  if (intent === "design_program") {
    return { ...base, specialists: ["MasterHRAgent", "ProgramDesignerAgent", "CommsPlannerAgent"], tools: ["program_designer", "comms_planner"], skills: ["hr-engagement-design", "game-selection", "communication-strategy", "artifact-composition"] };
  }
  if (intent === "analyze_data") {
    return { ...base, specialists: ["MasterHRAgent", "InsightsAnalystAgent"], tools: ["insights_analyst", "multi_dataset_query"], skills: ["data-analysis", "artifact-composition"] };
  }
  return { ...base, specialists: ["MasterHRAgent", "InsightsAnalystAgent", "ReportComposerAgent"], tools: ["insights_analyst", "report_composer", "multi_dataset_query"], skills: ["data-analysis", "executive-reporting", "artifact-composition"] };
}

/* ─── Build artifacts from AGENT output (AI-decided) ─── */

function buildAgentDecidedKpiDashboard(output: AgentChatOutput): ArtifactSpec | null {
  if (!output.kpis || output.kpis.length === 0) return null;
  return {
    id: createId("artifact"),
    kind: "kpi_dashboard",
    title: output.kpiTitle || "Dashboard",
    summary: output.kpiSummary || "Key metrics from your data.",
    kpis: output.kpis,
    insights: (output.insights ?? []).map((i) => i.text),
  };
}

function buildAgentDecidedTables(output: AgentChatOutput): ArtifactSpec[] {
  if (!output.tables || output.tables.length === 0) return [];
  return output.tables.map((t) => ({
    id: createId("artifact"),
    kind: "table_report" as const,
    title: t.title,
    summary: t.summary,
    columns: t.columns,
    rows: t.rows.map((row) => {
      const clean: Record<string, string | number> = {};
      for (const [k, v] of Object.entries(row)) {
        clean[k] = v == null ? "" : typeof v === "boolean" ? String(v) : (v as string | number);
      }
      return clean;
    }),
  }));
}

function buildAgentDecidedCharts(output: AgentChatOutput): ArtifactSpec | null {
  if (!output.charts || output.charts.length === 0) return null;
  return {
    id: createId("artifact"),
    kind: "chart_report",
    title: "Visual analysis",
    summary: output.reasoningSummary || "Charts chosen by the AI agent.",
    charts: output.charts.map((c) => ({
      id: createId("chart"),
      type: c.type,
      title: c.title,
      summary: c.summary,
      series: c.series,
    })),
  };
}

function buildAgentDecidedSlides(output: AgentChatOutput): ArtifactSpec | null {
  if (!output.slides || output.slides.length === 0) return null;
  return {
    id: createId("artifact"),
    kind: "slides_report",
    title: output.slideTitle || "Leadership summary",
    summary: output.reasoningSummary || "Report generated by AI.",
    slides: output.slides,
  };
}

function buildAgentDecidedIdeaBoard(output: AgentChatOutput): ArtifactSpec | null {
  if (!output.ideas || output.ideas.length === 0) return null;
  return {
    id: createId("artifact"),
    kind: "idea_board",
    title: "Ideas for your request",
    summary: output.reasoningSummary || "Program directions based on your brief.",
    followUpQuestion: output.followUpQuestion || "Which direction interests you?",
    ideas: output.ideas,
  };
}

function buildAgentDecidedProgram(output: AgentChatOutput): ArtifactSpec | null {
  if (!output.programDays || output.programDays.length === 0) return null;
  return {
    id: createId("artifact"),
    kind: "program_calendar",
    title: output.programTitle || "Program draft",
    objective: output.programObjective || "",
    cadence: output.programCadence || "",
    days: output.programDays.map((day) => ({
      dayLabel: day.dayLabel,
      theme: day.theme,
      focus: day.focus,
      activities: day.activities.map((a) => ({
        id: createId(a.type),
        type: a.type,
        title: a.title,
        description: a.description,
        template: null,
        recommendedDay: a.day,
        pollQuestions: a.pollQuestions,
        surveyQuestions: a.surveyQuestions,
      })),
    })),
  };
}

function buildAgentDecidedComms(output: AgentChatOutput): ArtifactSpec | null {
  if (!output.commsMessages || output.commsMessages.length === 0) return null;
  const channelsUsed = [...new Set(output.commsMessages.map((m) => m.channel))];
  return {
    id: createId("artifact"),
    kind: "comms_plan",
    title: `${output.programTitle || "Program"} communications plan`,
    channelsUsed,
    messages: output.commsMessages.map((m) => ({ id: createId("msg"), ...m, editableByHr: true })),
  };
}

/* ─── Main artifact assembly: PREFER agent content, fallback to templates ─── */

function buildArtifacts(input: {
  message: string;
  allDatasets: Dataset[];
  output: AgentChatOutput;
}): { artifacts: ArtifactSpec[]; datasetsUsed: string[]; agentDecided: boolean } & Omit<ChatResponse, "message" | "trace" | "artifacts"> {
  const { output, allDatasets } = input;

  /* ── BRAINSTORM ── */
  if (output.intent === "brainstorm") {
    const agentBoard = buildAgentDecidedIdeaBoard(output);
    if (agentBoard) {
      return { intent: output.intent, artifacts: [agentBoard], datasetsUsed: output.datasetsUsed ?? [], agentDecided: true };
    }
    return { intent: output.intent, artifacts: [buildIdeaBoardArtifact(input.message, allDatasets)], datasetsUsed: [], agentDecided: false };
  }

  /* ── DESIGN PROGRAM ── */
  if (output.intent === "design_program") {
    const agentProgram = buildAgentDecidedProgram(output);
    const agentComms = buildAgentDecidedComms(output);
    if (agentProgram) {
      const arts: ArtifactSpec[] = [agentProgram];
      if (agentComms) arts.push(agentComms);
      return { intent: output.intent, artifacts: arts, datasetsUsed: [], agentDecided: true };
    }
    const programDraft = generateProgramCalendar({ brief: input.message });
    return { intent: output.intent, programDraft, artifacts: [buildProgramCalendarArtifact(programDraft), buildCommsPlanArtifact(programDraft)], datasetsUsed: [], agentDecided: false };
  }

  /* ── ANALYZE DATA / BUILD REPORT ── */
  /* Try agent-decided artifacts first */
  const agentArtifacts: ArtifactSpec[] = [];
  const kpi = buildAgentDecidedKpiDashboard(output);
  if (kpi) agentArtifacts.push(kpi);
  const tables = buildAgentDecidedTables(output);
  agentArtifacts.push(...tables);
  const charts = buildAgentDecidedCharts(output);
  if (charts) agentArtifacts.push(charts);
  const slides = buildAgentDecidedSlides(output);
  if (slides) agentArtifacts.push(slides);

  if (agentArtifacts.length > 0) {
    return {
      intent: output.intent,
      artifacts: agentArtifacts,
      datasetsUsed: output.datasetsUsed ?? [],
      agentDecided: true,
    };
  }

  /* Fallback: deterministic analysis (safety net) */
  const multi = analyzeMultipleDatasets({ allDatasets, query: input.message });
  const datasetsUsed = multi.selectedDatasets.map((d) => d.name);
  const combinedAnalysis = {
    id: `multi-${Date.now()}`,
    datasetId: "multi",
    summary: multi.overallSummary,
    rowCount: multi.combinedMetricRows.length,
    columnCount: 3,
    keyFindings: multi.combinedFindings,
    metricRows: multi.combinedMetricRows,
  };

  const fallbackArtifacts: ArtifactSpec[] = [
    buildKpiDashboardArtifact({ analysis: combinedAnalysis, allDatasets }),
    buildTableArtifact(combinedAnalysis),
    buildChartReportArtifact(combinedAnalysis),
  ];
  if (output.intent === "build_report") {
    fallbackArtifacts.push(buildSlidesArtifact(combinedAnalysis));
  }

  return {
    intent: output.intent,
    analysis: combinedAnalysis,
    artifacts: fallbackArtifacts,
    datasetsUsed,
    agentDecided: false,
  };
}

/* ─── Main entry point ─── */

export async function runMasterAgent(input: {
  message: string;
  datasetId?: string;
  messages?: { role: "user" | "assistant"; content: string }[];
}): Promise<ChatResponse> {
  const apiKey = ensureOpenAiApiKeyLoaded();
  if (!apiKey) {
    throw new Error("OPENAI_API_KEY is missing. Add it to .env.local before using the Bokchoys copilot.");
  }

  const agentsModule = await import("@openai/agents");
  const { run } = agentsModule as any;
  const { createMasterAgent } = await import("@/lib/agents/master");
  const agent = await createMasterAgent();
  const classifiedIntent = classifyIntent(input.message);

  const allDatasets = ensureAllSampleDatasetsLoaded();
  const selectedDataset = input.datasetId ? getDatasetById(input.datasetId) : undefined;

  /* Build dataset catalog with sample rows for agent reasoning */
  const catalogLines = allDatasets.map((ds) => {
    const sample = ds.rows[0] ? JSON.stringify(ds.rows[0]) : "{}";
    return `- "${ds.name}" (${ds.rows.length} rows, cols: [${ds.columns.join(", ")}])\n  Sample: ${sample}`;
  });

  const quickStats: string[] = [];
  const programs = allDatasets.find((d) => d.name === "Programs");
  if (programs) {
    const active = programs.rows.filter((r) => r.status === "active").length;
    const completed = programs.rows.filter((r) => r.status === "completed").length;
    quickStats.push(`Programs: ${active} active, ${completed} completed`);
  }
  const pulse = allDatasets.find((d) => d.name === "Wellbeing Pulse");
  if (pulse) {
    const q1 = pulse.rows.filter((r) => r.quarter === "Q1 2025");
    if (q1.length > 0) {
      const avgStress = (q1.map((r) => Number(r.stress_score ?? 0)).reduce((a, b) => a + b, 0) / q1.length).toFixed(1);
      quickStats.push(`Q1 stress avg: ${avgStress}/5`);
    }
  }
  const engagement = allDatasets.find((d) => d.name === "Employee Engagement");
  if (engagement) {
    const q1 = engagement.rows.filter((r) => r.quarter === "Q1 2025");
    if (q1.length > 0) {
      const avgEnps = (q1.map((r) => Number(r.eNPS ?? 0)).reduce((a, b) => a + b, 0) / q1.length).toFixed(0);
      quickStats.push(`Q1 eNPS avg: ${avgEnps}`);
    }
  }

  const selectedNote = selectedDataset
    ? `\nUser selected: "${selectedDataset.name}". Prioritize this.`
    : "\nNo dataset selected. Pick relevant ones.";

  const datasetContext = `[SYSTEM CONTEXT: ${allDatasets.length} datasets available:\n${catalogLines.join("\n")}${selectedNote}\n\nQuick stats: ${quickStats.join(" | ")}\n\nDo NOT ask to upload data. Analyze directly.]`;

  /* Load structured output instructions from editable MD file */
  const structuredOutputHint = `\n\n${loadPrompt("structured-output-hint.md")}`;

  const chatHistory = input.messages && input.messages.length > 0
    ? input.messages.map((item) => `${item.role.toUpperCase()}: ${item.content}`).join("\n\n")
    : input.message;

  const transcript = `${datasetContext}${structuredOutputHint}\n\n${chatHistory}`;

  const result = await run(agent, transcript, {
    context: { classifiedIntent, allDatasets, selectedDataset, companyName: "Choys", productName: "Bokchoys" },
  });

  /* Sanitize agent output: coerce nulls in table rows to empty strings */
  const rawOutput = result?.finalOutput ?? result?.output ?? result;
  if (rawOutput?.tables) {
    for (const table of rawOutput.tables) {
      if (table?.rows) {
        table.rows = table.rows.map((row: any) => {
          const clean: Record<string, string | number> = {};
          for (const [k, v] of Object.entries(row)) {
            clean[k] = v == null ? "" : typeof v === "object" ? JSON.stringify(v) : v as string | number;
          }
          return clean;
        });
      }
    }
  }

  const output = AgentChatOutputSchema.parse(rawOutput);
  const { agentDecided, datasetsUsed, artifacts, ...rest } = buildArtifacts({ message: input.message, allDatasets, output });

  return ChatResponseSchema.parse({
    ...rest,
    artifacts,
    message: output.message,
    trace: buildTrace(output.intent, datasetsUsed, agentDecided),
  });
}
